test:
	@$(MAKE) -sk test-all

test-all:	test-scripts

test-scripts:
	curl -sLO https://www3.nd.edu/~pbui/teaching/cse.20289.sp24/static/txt/reading06/test_scripts.sh
	chmod +x test_scripts.sh
	./test_scripts.sh
